author: "anonymous"
title: "My Site"
carousel: 
  - active: active
    caption: Caption 1
    imageUrl: "http://placehold.it/1900x1080&text=Slide One"
  - caption: Caption 2
    imageUrl: "http://placehold.it/1900x1080&text=Slide Two"
  - caption: Caption 3
    imageUrl: "http://placehold.it/1900x1080&text=Slide Three"
  - caption: Caption 4
    imageUrl: "http://placehold.it/1900x1080&text=Slide Four"
homeHeading: "The Home-Heading above the UVP"
uvp: "This is the UVP, you can define it later"
about: 
  heading: "We've got what you need!"
  text: "This section is about us, and about our core services..."
services: 
  - icon: "fa-gift"
    heading: Service 1.
    text: "Description of the service... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod? "
    detailsUrl: "#"
  - icon: "fa-newspaper-o"
    heading: Service 2.
    text: "Description of the service... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod? "
    detailsUrl: "#"
  - icon: "fa-heart"
    heading: Service 4.
    text: "Description of the service... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis quae nulla aspernatur in alias at numquam rerum ea excepturi expedita tenetur assumenda voluptatibus eveniet incidunt dicta nostrum quod? "
    detailsUrl: "#"
portfolio: 
  heading: Select from our portfolio...
  projects: 
    - heading: Project One
      subHeading: Project Subheading
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde."
      photoUrl: "http://placehold.it/700x300"
      projectUrl: "portfolio-item.html"
    - heading: Project Two
      subHeading: Project Subheading
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde."
      photoUrl: "http://placehold.it/700x300"
      projectUrl: "portfolio-item.html"
    - heading: Project Three
      subHeading: Project Subheading
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde."
      photoUrl: "http://placehold.it/700x300"
      projectUrl: "portfolio-item.html"
    - heading: Project Four
      subHeading: Project Subheading
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde."
      photoUrl: "http://placehold.it/700x300"
      projectUrl: "portfolio-item.html"
  callToAction: "Start Now!"
team: 
  - name: ""
    title: ""
    description: ""
    facebookUrl: ""
    linkedInUrl: ""
    twitterUrl: ""
    photoUrl: ""
customers: 
  - name: ""
    title: ""
    description: ""
    facebookUrl: ""
    linkedInUrl: ""
    twitterUrl: ""
    photoUrl: ""
testimonials: []
contact: 
  text: "Ready to start your next project with us? Give us a call or send us an email and we will get back to you as soon as possible!"
  address: "3481 Melrose Place<br>Beverly Hills, CA 90210"
  businessHours: "Monday - Friday: 9:00 AM to 5:00 PM"
  mail: "contact@mydomain.com"
  phone: "(+??) ?????-???"

